spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
spring.datasource.username=root
spring.datasource.password=shivansh

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0

aws.access.key=AKIAS6QEFFKN7QZUKAGC
aws.secret.key=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
aws.region=ap-south-1
aws.bucket.name=billing-app-storage

jwt.secret.key=thisismysecretkeyfortheupcomingproject

razorpay.key.id=rzp_test_RdiYJaddWPBQaG
razorpay.key.secret=6k2Q8bZB0SvSkB7Cn7sh1UL6